In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define Vocabulary Size
voc_size = 10000

In [5]:
# One Hot Representation
one_hot_repr=[one_hot(words, voc_size)for words in sent]
one_hot_repr

[[4783, 5265, 901, 1661],
 [4783, 5265, 901, 7332],
 [4783, 9238, 901, 3859],
 [2565, 6631, 8402, 5476, 3103],
 [2565, 6631, 8402, 5476, 1460],
 [4666, 4783, 4917, 901, 434],
 [5546, 6170, 8301, 5476]]

In [6]:
# word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen= sent_length)
print(embedded_docs)

[[   0    0    0    0 4783 5265  901 1661]
 [   0    0    0    0 4783 5265  901 7332]
 [   0    0    0    0 4783 9238  901 3859]
 [   0    0    0 2565 6631 8402 5476 3103]
 [   0    0    0 2565 6631 8402 5476 1460]
 [   0    0    0 4666 4783 4917  901  434]
 [   0    0    0    0 5546 6170 8301 5476]]


In [9]:
# Feature representation
dim=10

In [10]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 3s 3s/step


array([[[-2.47581135e-02, -2.38300692e-02, -3.79177816e-02,
          3.04479636e-02, -1.38125792e-02,  3.00892331e-02,
          4.13160212e-02, -3.16112787e-02,  6.30433485e-03,
          4.83917072e-03],
        [-2.47581135e-02, -2.38300692e-02, -3.79177816e-02,
          3.04479636e-02, -1.38125792e-02,  3.00892331e-02,
          4.13160212e-02, -3.16112787e-02,  6.30433485e-03,
          4.83917072e-03],
        [-2.47581135e-02, -2.38300692e-02, -3.79177816e-02,
          3.04479636e-02, -1.38125792e-02,  3.00892331e-02,
          4.13160212e-02, -3.16112787e-02,  6.30433485e-03,
          4.83917072e-03],
        [-2.47581135e-02, -2.38300692e-02, -3.79177816e-02,
          3.04479636e-02, -1.38125792e-02,  3.00892331e-02,
          4.13160212e-02, -3.16112787e-02,  6.30433485e-03,
          4.83917072e-03],
        [-8.10623169e-04,  1.44949444e-02,  5.13134152e-03,
          1.81383602e-02, -4.24112454e-02,  3.67887132e-02,
          8.92049074e-03,  3.93636860e-02,  6.174243

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 4783, 5265,  901, 1661])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 88ms/step


array([[-0.02475811, -0.02383007, -0.03791778,  0.03044796, -0.01381258,
         0.03008923,  0.04131602, -0.03161128,  0.00630433,  0.00483917],
       [-0.02475811, -0.02383007, -0.03791778,  0.03044796, -0.01381258,
         0.03008923,  0.04131602, -0.03161128,  0.00630433,  0.00483917],
       [-0.02475811, -0.02383007, -0.03791778,  0.03044796, -0.01381258,
         0.03008923,  0.04131602, -0.03161128,  0.00630433,  0.00483917],
       [-0.02475811, -0.02383007, -0.03791778,  0.03044796, -0.01381258,
         0.03008923,  0.04131602, -0.03161128,  0.00630433,  0.00483917],
       [-0.00081062,  0.01449494,  0.00513134,  0.01813836, -0.04241125,
         0.03678871,  0.00892049,  0.03936369,  0.00617424, -0.0264585 ],
       [ 0.03419591, -0.04102011, -0.02411313,  0.03010771, -0.03884058,
        -0.03609503,  0.04187467,  0.03085228, -0.01954889, -0.02575076],
       [ 0.0332209 ,  0.04090761,  0.01027475,  0.00716873, -0.00404023,
        -0.00732101, -0.03507562,  0.00369968